permalink: /:title.html
destination: serve
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
author: Ethan Cerami
web: http://biobits.org
email: cerami@gmail.com
twitter: ecerami
github: ecerami
linkedin: ecerami
base-url: /biobits
title:  BioBits - A Blog about bioinformatics, scientific computing and cancer genomics.
production_url:  http://biobits.org
